CREATE DATABASE FERRETERIAS
GO
USE FERRETERIAS
GO
CREATE TABLE ZONAS (
ZONAID INT NOT NULL,
ZONANOMBRE NVARCHAR(50) NOT NULL,
ZONADESCRIPCION NVARCHAR(200) NOT NULL)
GO 
SELECT * FROM ZONAS
GO
CREATE TABLE MUNICIPIOS(
MUNID INT NOT NULL,
MUNNOMBRE NVARCHAR (50) NOT NULL)
GO
CREATE TABLE COLONIAS(
COLID INT NOT NULL,
COLNOMBRE NVARCHAR (50) NOT NULL,
COLCP NCHAR(5) NULL,
MUNID INT NOT NULL)
GO
CREATE TABLE FAMILIAS(
FAMID INT NOT NULL,
FAMNOMBRE NVARCHAR (50) NOT NULL,
FAMDESCRIPCION NVARCHAR(200) NOT NULL)
GO
CREATE TABLE FERRETERIAS(
FERRID INT NOT NULL,
FERRNOMBRE NVARCHAR (20) NOT NULL,
FERRDOMICILIO NVARCHAR (50) NOT NULL,
FERRTELEFONO NCHAR (10) NOT NULL)
GO 
CREATE TABLE EMPLEADOS(
EMPID INT NOT NULL,
EMPNOMBRE NVARCHAR (50) NOT NULL,
EMPAPEPAT NVARCHAR (50) NOT NULL,
EMPAPEMAT NVARCHAR (50) NULL,
EMPDOMICILIO NVARCHAR (50) NOT NULL,
EMPTELEFONO NCHAR (10) NULL,
EMPCELULAR NCHAR (10) NULL,
EMPRFC NCHAR (13) NULL,
EMPCURP NCHAR (18) NULL,
EMPFECHAINGRESO DATETIME NOT NULL,
EMPFECHANACIMIENTO DATETIME NOT NULL,
ZONAID INT NOT NULL,
JEFEID INT NULL)
GO
CREATE TABLE CLIENTES(
CTEID INT NOT NULL,
CTENOMBRE NVARCHAR (50) NOT NULL,
CTEAPEPAT NVARCHAR (50) NOT NULL,
CTEAPEMAT NVARCHAR (50) NULL,
CTEDOMICILIO NVARCHAR (50) NOT NULL,
CTETELEFONO NCHAR (10) NULL,
CTECELULAR NCHAR (10) NULL,
CTERFC NCHAR (13) NULL,
CTECURP NCHAR (18) NULL,
EMCTEFECHANACIMIENTO DATETIME NOT NULL,
CTESEXO NCHAR (1) NOT NULL,
COLID INT NOT NULL)
GO
CREATE TABLE ARTICULOS(
ARTID INT NOT NULL,
ARTNOMBRE NVARCHAR (50) NOT NULL,
ARTDESCRIPCION NVARCHAR (200) NOT NULL,
ARTPRECIO NUMERIC (10,2) NOT NULL,
FAMID INT NOT NULL)
GO
CREATE TABLE VENTAS(
FOLIO INT NOT NULL,
FECHA DATETIME NOT NULL,
FERRID INT NOT NULL,
CTEID INT NOT NULL,
EMPID INT NOT NULL)
GO
CREATE TABLE DETALLE(
FOLIO INT NOT NULL,
ARTID INT NOT NULL,
CANTIDAD NUMERIC (7,2) NOT NULL,
PRECIO NUMERIC (10,2) NOT NULL)
SELECT*FROM DETALLE
SELECT*FROM CLIENTES
GO

ALTER TABLE ZONAS ADD CONSTRAINT PK_ZONAS PRIMARY KEY (ZONAID)

DELETE ZONAS
--INSERT
INSERT ZONAS VALUES(1,'Norte','Zona Norte')
INSERT ZONAS VALUES(2,'Sur','Zona Sur')
INSERT ZONAS VALUES(3,'Oeste','Zona Oeste')
INSERT ZONAS VALUES(4,'Este','Zona Este')

SELECT * FROM ZONAS
--CONSTRAINT
ALTER TABLE DETALLE ADD CONSTRAINT PK_DETALLE PRIMARY KEY(FOLIO,ARTID)

ALTER TABLE MUNICIPIOS ADD CONSTRAINT PK_MUNICIPIOS PRIMARY KEY(MUNID)
ALTER TABLE COLONIAS ADD CONSTRAINT PK_COLONIAS PRIMARY KEY(COLID)
ALTER TABLE EMPLEADOS ADD CONSTRAINT PK_EMPLEADOS PRIMARY KEY(EMPID)
ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES PRIMARY KEY(CTEID)
ALTER TABLE ARTICULOS ADD CONSTRAINT PK_ARTICULOS PRIMARY KEY(ARTID)
ALTER TABLE FAMILIAS ADD CONSTRAINT PK_FAMILIAS PRIMARY KEY(FAMID)
ALTER TABLE VENTAS ADD CONSTRAINT PK_VENTAS PRIMARY KEY(FOLIO)
ALTER TABLE FERRETERIAS ADD CONSTRAINT PK_FERRETERIAS PRIMARY KEY(FERRID)

GO
-- IDENTITY

USE FERRETERIAS
CREATE TABLE EMPRESAS(
CLAVE INT NOT NULL IDENTITY(100,2),
NOMBRE VARCHAR (100) NOT NULL,
DOMICILIO VARCHAR (100) NULL)
--Es necesario omitir el valor de identidad al insertar
INSERT EMPRESAS VALUES( 'tiendas lopez','av obregon 43')
INSERT EMPRESAS VALUES( 'tiendas LEY','av obregon 345')
INSERT EMPRESAS VALUES( 'tiendas DEL CENTRO','av obregon 345')
SELECT*FROM EMPRESAS
--No se puede actualizar el valor identidad
UPDATE EMPRESAS SET CLAVE = 101 WHERE CLAVE = 100
--Al eliminar un registro, el contador del identity continua, no se reincia
DELETE EMPRESAS
--El valor continua con 106
INSERT EMPRESAS VALUES('tienda lopez','av obregon 43')
SELECT*FROM EMPRESAS
--Variable de sistema para mostrar el ultimo valor identity
SELECT @@IDENTITY
--Con truncate table se reincia el valor de la identidad
TRUNCATE TABLE EMPRESAS
--Se reinicia en 100 el valor identity
INSERT EMPRESAS VALUES ('tiendas lopez','av obregon 43')